String apikey = "1a293e95586772bd247c623d5bd9ec55";
var kTrendingweekurl =
    'https://api.themoviedb.org/3/trending/all/week?api_key=$apikey';
var kTrendingdayurl =
    'https://api.themoviedb.org/3/trending/all/day?api_key=$apikey';
var kTopRatedTvSeries =
    'https://api.themoviedb.org/3/tv/top_rated?api_key=$apikey';
var kPopularTvSeries =
    'https://api.themoviedb.org/3/tv/popular?api_key=$apikey';
var kOnAirTvSeries =
    'https://api.themoviedb.org/3/tv/on_the_air?api_key=$apikey';
var kTopRatedMovies =
    'https://api.themoviedb.org/3/movie/top_rated?api_key=$apikey';
var kPopularMovies =
    'https://api.themoviedb.org/3/movie/popular?api_key=$apikey';
var kLatestmoviesurl =
    'https://api.themoviedb.org/3/movie/latest?api_key=$apikey';
var kNowplayingmoviesurl =
    'https://api.themoviedb.org/3/movie/now_playing?api_key=$apikey';
